### ISSUE TITLE
Logo for better-picker-android

### ISSUE THREAD

**Issue by familqasimov** [afollestad/better-picker-android#1]
Hi sir. I'm graphic designer. I have studied your work and I think a new design will make you more visible. I would like to offer logo. I can give you all the formats of the design free. If you want I send you PR or a change please specify.

![better pickers for android](https://user-images.githubusercontent.com/36432269/39666261-f101f788-50b1-11e8-8017-0e1c1907cf19.png)

**Comment by afollestad** [comment]
Thanks, but I don't feel that is necessary.
